#ifndef CONSTS_H_
#define CONSTS_H_

#define SERVER_ADDRESS 0x01
#define REQUEST_CODE 0x23
#define REQUEST_INTERNAL_TEMPERATURE 0xC1
#define REQUEST_REFERENCE_TEMPERATURE 0xC2
#define REQUEST_USER_CMD 0xC3
#define SEND_CODE 0x16
#define SEND_CONTROL_SIGNAL 0xD1
#define SEND_REFERENCE_SIGNAL 0xD2
#define SEND_SYSTEM_STATE 0xD3
#define SEND_WORKING_STATE 0xD5
#define SEND_TIMER_VALUE 0xD6

#endif 
